color=["red","green","black"]
      print(color)
      number=[7,9,3,0,2,7,6]
             print(number)
             number.sort()
             print(number)
             number.reverse()
             print(number)
             print(number[ : ])
             print(number[ 0:5 ])
             print(number[0 : :2])
             print(max(number))
             print(min(number))
             number.append(56)
             print(number)
             number.insert(1,99)
             print(number)
             number.remove(99)
             print(number)
             number.pop()
             print(number)
